[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x", "openssl"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]
cacheDirectories = ["/root/.local/share/pnpm/store/v10-1781728735"]

[phases.build]
cmds = [
  "find . -name dist -type d | xargs rm -rf",
  "pnpm run typecheck:libs",
  "pnpm --filter @workspace/api-spec run codegen",
  "pnpm --filter @workspace/api-server run build",
  "BASE_PATH=/ pnpm --filter @workspace/pay-it-forward run build"
]

[start]
cmd = "node --enable-source-maps artifacts/api-server/dist/index.mjs"
