import assert from "node:assert/strict";
import fs from "node:fs";

const rail = fs.readFileSync("artifacts/pay-it-forward/src/components/community/CommunityStoryRail.tsx", "utf8");
const shell = fs.readFileSync("artifacts/pay-it-forward/src/components/community/CommunityStoriesExperience.tsx", "utf8");
const communityPage = fs.readFileSync("artifacts/pay-it-forward/src/pages/community.tsx", "utf8");
const interactionClient = fs.readFileSync("artifacts/pay-it-forward/src/lib/community-story-client.ts", "utf8");
const interactions = fs.readFileSync("artifacts/api-server/src/routes/community-story-interactions.ts", "utf8");
const storyRoutes = fs.readFileSync("artifacts/api-server/src/routes/community-stories.ts", "utf8");
const messages = fs.readFileSync("artifacts/api-server/src/routes/direct-messages.ts", "utf8");
const scheduler = fs.readFileSync("artifacts/api-server/src/lib/scheduler.ts", "utf8");

assert.match(rail, /StoryMediaPlayer/);
assert.match(rail, /StoryShareSheet/);
assert.match(rail, /\/api\/community\/stories/);
assert.match(shell, /export function CommunityStoriesExperience/);
assert.match(communityPage, /CommunityStoriesView/);
assert.doesNotMatch(communityPage, /<CommunityStoryRail/);
assert.match(rail, /sendStoryContextMessage/);
assert.match(rail, /storyId: selectedStory\.id/);
assert.match(interactionClient, /story_id: input\.storyId/);
assert.match(interactions, /communityStoryViewsTable/);
assert.match(interactions, /communityStoryReactionsTable/);
assert.match(interactions, /communityStorySharesTable/);
assert.match(storyRoutes, /moderation\.status === "approved" \? "published" : "pending"/);
assert.match(storyRoutes, /streamAssetSameOrigin\(row\.variant_key \?\? row\.storage_key, res\)/);
assert.match(messages, /application\/x-niakofa-story\+json/);
assert.match(messages, /communityStoriesTable/);
assert.match(scheduler, /startCommunityStoryCleanupWorker/);
assert.match(rail, /gallerySelection/);
assert.match(rail, /selectedIndexes/);
assert.match(rail, /event\.key === "Escape"/);
assert.match(rail, /event\.key === "ArrowRight"/);
assert.match(rail, /onSwipe/);
assert.match(rail, /onHoldChange/);
assert.match(rail, /paused=\{storyPaused\}/);
assert.match(rail, /direction === "close"/);
assert.match(rail, /autoOpenedRef/);
assert.doesNotMatch(rail, /nia-story-discovery/);
assert.match(fs.readFileSync("artifacts/pay-it-forward/src/components/community/community-story-visual.css", "utf8"), /width:100vw; height:100dvh/);
assert.doesNotMatch(rail, /\/api\/messages\/stories/);
assert.doesNotMatch(messages, /message_stories/);
