/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useMemo, useState } from "react";
import Map, { Layer, Marker, Source } from "react-map-gl/mapbox";
import "mapbox-gl/dist/mapbox-gl.css";
import { AlertTriangle, ArrowLeft, BookOpen, Check, Flag, Globe2, Languages, MapPin, Mic, Pause, Play, RefreshCw, Send, Users, Volume2 } from "lucide-react";
import { useLocation } from "wouter";
import { useAppContext } from "@/lib/AppContext";
import { authHeaders } from "@/lib/auth";
import { toast } from "@/hooks/use-toast";
import { diasporaTheme } from "@/lib/diaspora/theme";

type Hub = { id: number; name: string; region: string; lat: number; lng: number; tag: string; story_count: number; member_count: number; open_requests: number; reserved_balance?: string | number | null; activity: { active_helpers: number; requests_fulfilled: number; pool_balance: number } | null; is_crisis: boolean; crisis_message: string | null };
type Story = { id: number; author_id: number; title: string | null; text_content: string | null; audio_url: string | null; original_language: string; hub_location: string | null; lat: number | null; lng: number | null; duration_seconds: number | null; published_at: string | null };
type Translation = { id: number; story_id: number; language: string; nia_draft_text: string | null; edited_text: string | null; recorder_approved: boolean };
const token = import.meta.env.VITE_MAPBOX_TOKEN as string | undefined;
const fallbackHome = { lat: 32.75, lng: -97.33 };
function arcs(hubs: Hub[]) { const home = hubs.find(h => h.tag === "home") ?? fallbackHome; return { type: "FeatureCollection" as const, features: hubs.filter(h => h.tag !== "home").map(h => ({ type: "Feature" as const, properties: { id: h.id }, geometry: { type: "LineString" as const, coordinates: [[home.lng, home.lat], [h.lng, h.lat]] } })) }; }
function lang(code: string) { return ({ en: "English", es: "Español", fr: "Français", pt: "Português", ht: "Kreyòl", sw: "Kiswahili", yo: "Yorùbá", ar: "العربية", am: "አማርኛ", ha: "Hausa", ig: "Igbo", tw: "Twi", wo: "Wolof", zu: "isiZulu" } as Record<string, string>)[code] ?? code.toUpperCase(); }

export default function GlobePage() {
  const { currentUser } = useAppContext(); const [, navigate] = useLocation();
  const [hubs, setHubs] = useState<Hub[]>([]); const [stories, setStories] = useState<Story[]>([]); const [selectedHub, setSelectedHub] = useState<Hub | null>(null); const [selectedStory, setSelectedStory] = useState<Story | null>(null); const [translations, setTranslations] = useState<Translation[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [playing, setPlaying] = useState(false); const [audio, setAudio] = useState<HTMLAudioElement | null>(null); const [reporting, setReporting] = useState(false); const [reportReason, setReportReason] = useState(""); const [savingTranslation, setSavingTranslation] = useState(false);
  async function load() { setRefreshing(true); try { const [h, s] = await Promise.all([fetch("/api/griot/hubs", { headers: authHeaders() }), fetch("/api/griot/stories?limit=20", { headers: authHeaders() })]); if (h.ok) { const data = await h.json(); setHubs(data.hubs ?? []); } if (s.ok) { const data = await s.json(); setStories(data.stories ?? []); } } catch { toast({ title: "Couldn't refresh the Globe", variant: "destructive" }); } finally { setLoading(false); setRefreshing(false); } }
  useEffect(() => { if (!currentUser) return; void load(); return () => { audio?.pause(); }; }, [currentUser]);
  async function selectStory(story: Story) { setSelectedStory(story); setReporting(false); setReportReason(""); try { const r = await fetch(`/api/griot/stories/${story.id}/translations`, { headers: authHeaders() }); if (r.ok) { const data = await r.json(); setTranslations(data.translations ?? []); } else setTranslations([]); } catch { setTranslations([]); } }
  function playStory(story: Story) { if (!story.audio_url) return; audio?.pause(); const next = new Audio(story.audio_url); next.onended = () => setPlaying(false); next.play().then(() => { setAudio(next); setPlaying(true); }).catch(() => { setPlaying(false); toast({ title: "Audio couldn't play", variant: "destructive" }); }); }
  function toggleStory(story: Story) { if (audio && selectedStory?.id === story.id && playing) { audio.pause(); setPlaying(false); return; } playStory(story); }
  async function approveTranslation(t: Translation, edited: string) { setSavingTranslation(true); try { const r = await fetch(`/api/griot/stories/${t.story_id}/translations/${t.language}/approve`, { method: "PATCH", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify(edited.trim() ? { edited_text: edited.trim() } : {}) }); if (!r.ok) throw new Error(); toast({ title: "Translation approved" }); await selectStory(selectedStory!); } catch { toast({ title: "Translation approval failed", variant: "destructive" }); } finally { setSavingTranslation(false); } }
  async function reportStory() { if (!currentUser || !selectedStory || reportReason.trim().length < 10) { toast({ title: "Describe the issue in at least 10 characters", variant: "destructive" }); return; } try { const r = await fetch("/api/reports", { method: "POST", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify({ reporter_id: currentUser.id, reported_griot_story_id: selectedStory.id, type: "other", description: reportReason.trim() }) }); if (!r.ok) throw new Error(); setReporting(false); setReportReason(""); toast({ title: "Report submitted for review" }); } catch { toast({ title: "Couldn't submit report", variant: "destructive" }); } }
  const visibleStories = useMemo(() => selectedHub ? stories.filter(s => s.hub_location === selectedHub.name || (s.lat != null && s.lng != null && Math.abs(s.lat - selectedHub.lat) < 2 && Math.abs(s.lng - selectedHub.lng) < 2)) : stories, [stories, selectedHub]);
  const totalStories = hubs.reduce((n, h) => n + (h.story_count || 0), 0); const totalMembers = hubs.reduce((n, h) => n + (h.member_count || 0), 0);
  if (!currentUser) return <div className="min-h-screen flex items-center justify-center">Sign in to enter the Diaspora Globe.</div>;
  if (!token) return <div className={`${diasporaTheme.page} min-h-screen p-6`}><button onClick={() => navigate("/diaspora")} className="mb-6 flex items-center gap-2"><ArrowLeft className="w-4 h-4" /> Diaspora</button><div className="max-w-xl mx-auto p-6 rounded-2xl border border-amber-300/20 bg-amber-300/10"><h1 className="font-bold text-xl">Globe needs a Mapbox token</h1><p className="text-sm text-white/60 mt-2">Set VITE_MAPBOX_TOKEN in the web app environment to enable the interactive globe.</p></div></div>;
  return <div className={`${diasporaTheme.page} min-h-screen pb-20`}>
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#071312]/85 backdrop-blur-xl"><div className="max-w-7xl mx-auto px-4 py-3 flex items-center gap-3"><button onClick={() => navigate("/diaspora")} className={`p-2 rounded-xl ${diasporaTheme.focus}`}><ArrowLeft className="w-5 h-5" /></button><div className="flex-1"><p className="font-semibold flex items-center gap-2"><Globe2 className="w-4 h-4 text-teal-300" /> Diaspora Globe</p><p className="text-xs text-white/45">A living map of family stories, community memory, and migration</p></div><button onClick={() => void load()} disabled={refreshing} className="p-2 rounded-xl border border-white/10 hover:bg-white/5"><RefreshCw className={`w-4 h-4 ${refreshing ? "animate-spin" : ""}`} /></button><button onClick={() => navigate("/diaspora/family?intent=oral-history")} className="hidden sm:flex items-center gap-2 rounded-xl bg-rose-300/10 text-rose-200 border border-rose-300/20 px-3 py-2 text-xs"><Mic className="w-3 h-3" /> Record a story</button></div></header>
    <main className="max-w-7xl mx-auto px-4 pt-5 space-y-5">
      <section className={`${diasporaTheme.radiusHero} overflow-hidden border border-teal-300/20 bg-gradient-to-br from-teal-300/10 via-[#071312] to-amber-300/10 ${diasporaTheme.shadow}`}><div className="p-6 md:p-8"><p className="text-xs uppercase tracking-[0.22em] text-teal-300">Globe → Family → Stories</p><h1 className="text-3xl md:text-5xl font-bold mt-2 leading-tight">See where your family's memory lives.</h1><p className="text-sm md:text-base text-white/60 mt-3 max-w-3xl">Move from a place on the map into people, voices, heritage, research, and Legacy stories. Hub counts and story pins come from the live Griot APIs.</p><div className="flex flex-wrap gap-3 mt-6"><div className="px-3 py-2 rounded-xl bg-white/5 border border-white/10"><p className="text-lg font-bold">{hubs.length}</p><p className="text-[11px] text-white/45">living hubs</p></div><div className="px-3 py-2 rounded-xl bg-white/5 border border-white/10"><p className="text-lg font-bold">{totalStories}</p><p className="text-[11px] text-white/45">hub stories</p></div><div className="px-3 py-2 rounded-xl bg-white/5 border border-white/10"><p className="text-lg font-bold">{totalMembers}</p><p className="text-[11px] text-white/45">hub members*</p></div></div></div>
        <div className="h-[52vh] min-h-[430px] relative">{loading && <div className="absolute inset-0 z-10 flex items-center justify-center bg-[#071312]/70"><div className="rounded-xl bg-black/40 px-4 py-2 text-sm text-white/70">Loading the living map…</div></div>}<Map initialViewState={{ longitude: -20, latitude: 18, zoom: 1.35 }} projection="globe" mapStyle="mapbox://styles/mapbox/dark-v11" mapboxAccessToken={token} attributionControl={false}><Source id="diaspora-arcs" type="geojson" data={arcs(hubs)}><Layer id="diaspora-arc-lines" type="line" paint={{ "line-color": "#f59e0b", "line-opacity": 0.28, "line-width": 1.4, "line-dasharray": [2, 2] }} /></Source>{hubs.map(h => <Marker key={h.id} longitude={h.lng} latitude={h.lat} anchor="center"><button onClick={() => { setSelectedHub(h); setSelectedStory(null); }} className={`relative group w-9 h-9 rounded-full border-2 ${h.is_crisis ? "border-rose-300 bg-rose-300/30" : h.tag === "home" ? "border-amber-300 bg-amber-300/30" : "border-teal-300 bg-teal-300/25"} shadow-lg`} title={h.name}><span className="absolute inset-1 rounded-full border border-white/30 animate-pulse" /></button></Marker>)}</Map><div className="absolute left-4 bottom-4 px-3 py-2 rounded-xl bg-[#071312]/85 border border-white/10 text-[11px] text-white/55">*Hub members are hub-level counts, not guaranteed unique people across hubs.</div></div></section>
      {selectedHub && <section className={`${diasporaTheme.panelStrong} ${diasporaTheme.radius} p-5`}><div className="flex flex-col md:flex-row md:items-start gap-4"><div className="flex-1"><div className="flex items-center gap-2"><MapPin className="w-4 h-4 text-teal-300" /><h2 className="font-semibold">{selectedHub.name}</h2>{selectedHub.is_crisis && <span className="px-2 py-1 rounded-full bg-rose-300/10 text-rose-200 text-[10px] inline-flex items-center gap-1"><AlertTriangle className="w-3 h-3" /> Crisis</span>}</div><p className="text-xs text-white/45 mt-1">{selectedHub.region} · {selectedHub.member_count} hub members · {selectedHub.story_count} stories</p>{selectedHub.crisis_message && <p className="text-sm text-rose-100/75 mt-3">{selectedHub.crisis_message}</p>}</div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-center text-[11px]"><div className="px-3 py-2 rounded-xl bg-white/5"><Users className="w-4 h-4 mx-auto text-teal-300" /><b className="block mt-1">{selectedHub.activity?.active_helpers ?? 0}</b><span className="text-white/40">helpers</span></div><div className="px-3 py-2 rounded-xl bg-white/5"><Send className="w-4 h-4 mx-auto text-emerald-300" /><b className="block mt-1">{selectedHub.activity?.requests_fulfilled ?? 0}</b><span className="text-white/40">fulfilled</span></div><div className="px-3 py-2 rounded-xl bg-white/5"><Flag className="w-4 h-4 mx-auto text-amber-300" /><b className="block mt-1">{selectedHub.open_requests}</b><span className="text-white/40">open requests</span></div><div className="px-3 py-2 rounded-xl bg-white/5"><b className="block mt-1">{selectedHub.activity?.pool_balance ?? 0}</b><span className="text-white/40">pool activity</span></div></div></div></section>}
      <section className="grid lg:grid-cols-[320px_1fr] gap-5"><aside className={`${diasporaTheme.panel} ${diasporaTheme.radius} p-4`}><div className="flex items-center justify-between"><h2 className="font-semibold">Places in the story</h2><span className="text-xs text-white/40">{hubs.length}</span></div><div className="space-y-2 mt-3">{hubs.map(h => <button key={h.id} onClick={() => { setSelectedHub(h); setSelectedStory(null); }} className={`w-full text-left rounded-xl border p-3 ${selectedHub?.id === h.id ? "border-teal-300/30 bg-teal-300/10" : "border-white/10 bg-white/[0.025]"}`}><div className="flex items-start gap-3"><MapPin className="w-4 h-4 text-teal-300 mt-0.5" /><div className="min-w-0 flex-1"><p className="text-sm font-medium truncate">{h.name}</p><p className="text-xs text-white/45">{h.region}</p><div className="flex gap-3 mt-2 text-[10px] text-white/45"><span>{h.story_count} stories</span><span>{h.member_count} members</span>{h.is_crisis && <span className="text-rose-300">crisis</span>}</div></div></div></button>)}</div></aside>
        <div className={`${diasporaTheme.panel} ${diasporaTheme.radius} p-4`}><div className="flex items-center justify-between"><div><h2 className="font-semibold">Voices from the map</h2><p className="text-xs text-white/45">{selectedHub ? selectedHub.name : "Across the diaspora"}</p></div></div><div className="grid md:grid-cols-2 gap-3 mt-4">{visibleStories.slice(0, 8).map(s => <article key={s.id} className={`rounded-xl border p-4 ${selectedStory?.id === s.id ? "border-teal-300/30 bg-teal-300/5" : "border-white/10 bg-white/[0.025]"}`}><button className="w-full text-left" onClick={() => void selectStory(s)}><div className="flex gap-3"><div className="w-10 h-10 rounded-full bg-rose-300/10 border border-rose-300/20 flex items-center justify-center"><BookOpen className="w-4 h-4 text-rose-300" /></div><div className="flex-1 min-w-0"><h3 className="font-medium text-sm line-clamp-2">{s.title || "Untitled family story"}</h3><p className="text-[11px] text-white/40 mt-1">{lang(s.original_language)} · {s.hub_location || "Diaspora"}</p>{s.text_content && <p className="text-xs text-white/55 mt-2 line-clamp-3">{s.text_content}</p>}</div></div></button>{s.audio_url && <button onClick={() => { void selectStory(s); toggleStory(s); }} className="mt-3 inline-flex items-center gap-2 text-xs text-teal-300"><span className="w-7 h-7 rounded-full bg-teal-300/10 flex items-center justify-center">{selectedStory?.id === s.id && playing ? <Pause className="w-3 h-3" /> : <Play className="w-3 h-3" />}</span><Volume2 className="w-3 h-3" /> {selectedStory?.id === s.id && playing ? "Playing" : "Listen"}</button>}</article>)}{!visibleStories.length && <div className="md:col-span-2 text-sm text-white/45 py-8 text-center">No published stories are attached to this place yet. Be the first to record one.</div>}</div></div></section>
      {selectedStory && <section className={`${diasporaTheme.panelStrong} ${diasporaTheme.radius} p-5`}><div className="flex flex-col lg:flex-row gap-5"><div className="flex-1"><div className="flex items-center gap-2"><BookOpen className="w-5 h-5 text-rose-300" /><h2 className="font-semibold">Story detail</h2></div><p className="text-lg font-bold mt-2">{selectedStory.title || "Untitled family story"}</p><p className="text-xs text-white/45 mt-1">{lang(selectedStory.original_language)} · {selectedStory.hub_location || "Diaspora"}</p>{selectedStory.text_content && <p className="font-serif text-sm leading-7 text-white/75 mt-4">{selectedStory.text_content}</p>}<div className="flex flex-wrap gap-2 mt-4"><button onClick={() => navigate("/diaspora/family?intent=oral-history")} className="inline-flex items-center gap-2 px-3 py-2 rounded-lg bg-rose-300/10 text-rose-200 text-xs"><Mic className="w-3 h-3" /> Record your story</button><button onClick={() => setReporting(v => !v)} className="inline-flex items-center gap-2 px-3 py-2 rounded-lg border border-white/10 text-xs text-white/60"><Flag className="w-3 h-3" /> Report</button></div>{reporting && <div className="mt-3 space-y-2"><textarea value={reportReason} onChange={e => setReportReason(e.target.value)} placeholder="What should a moderator review?" className="w-full min-h-20 rounded-xl bg-white/5 border border-white/10 px-3 py-2 text-sm" /><button onClick={() => void reportStory()} className="px-3 py-2 rounded-lg bg-rose-300 text-black text-xs font-semibold">Submit report</button></div>}</div><div className="lg:w-[360px] border-t lg:border-t-0 lg:border-l border-white/10 pt-4 lg:pt-0 lg:pl-5"><div className="flex items-center gap-2 font-semibold"><Languages className="w-4 h-4 text-teal-300" /> Translation review</div>{translations.length ? <div className="space-y-3 mt-3">{translations.map(t => <TranslationRow key={t.id} translation={t} saving={savingTranslation} onApprove={approveTranslation} />)}</div> : <p className="text-xs text-white/45 mt-3">No translation drafts are attached to this story yet.</p>}</div></div></section>}
      <section className="grid sm:grid-cols-3 gap-3"><button onClick={() => navigate("/diaspora/family")} className="p-4 rounded-xl border border-emerald-300/20 bg-emerald-300/10 text-left"><Users className="w-5 h-5 text-emerald-300" /><p className="font-semibold mt-3">Family</p><p className="text-xs text-white/45 mt-1">Open the people behind the places.</p></button><button onClick={() => navigate("/diaspora/research")} className="p-4 rounded-xl border border-amber-300/20 bg-amber-300/10 text-left"><BookOpen className="w-5 h-5 text-amber-300" /><p className="font-semibold mt-3">Research</p><p className="text-xs text-white/45 mt-1">Turn clues into a reviewable proof chain.</p></button><button onClick={() => navigate("/diaspora/dna")} className="p-4 rounded-xl border border-rose-300/20 bg-rose-300/10 text-left"><Globe2 className="w-5 h-5 text-rose-300" /><p className="font-semibold mt-3">Connections</p><p className="text-xs text-white/45 mt-1">Review consented DNA signals with genealogy evidence.</p></button></section>
    </main></div>;
}
function TranslationRow({ translation, saving, onApprove }: { translation: Translation; saving: boolean; onApprove: (translation: Translation, edited: string) => Promise<void> }) { const [text, setText] = useState(translation.edited_text || translation.nia_draft_text || ""); return <div className="rounded-xl border border-white/10 bg-white/[0.025] p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium">{lang(translation.language)}</p><span className={`text-[10px] px-2 py-1 rounded-full ${translation.recorder_approved ? "bg-emerald-300/10 text-emerald-300" : "bg-amber-300/10 text-amber-200"}`}>{translation.recorder_approved ? "Approved" : "Pending review"}</span></div><textarea value={text} onChange={e => setText(e.target.value)} className="w-full mt-2 min-h-20 rounded-lg bg-white/5 border border-white/10 px-2 py-2 text-xs" disabled={translation.recorder_approved} /><button onClick={() => void onApprove(translation, text)} disabled={saving || translation.recorder_approved} className="mt-2 inline-flex items-center gap-1 rounded-lg bg-emerald-300/10 text-emerald-300 px-2 py-1.5 text-[11px] disabled:opacity-40"><Check className="w-3 h-3" /> Approve translation</button></div>; }
