/**
 * Explicit column select for users table — excludes geog and password_hash.
 * Import wherever you need a safe, full user row without sensitive fields.
 */
import { usersTable } from "@workspace/db";

export const userSelect = {
  id: usersTable.id,
  name: usersTable.name,
  email: usersTable.email,
  avatar_url: usersTable.avatar_url,
  is_helper: usersTable.is_helper,
  helper_mode_active: usersTable.helper_mode_active,
  helper_status: usersTable.helper_status,
  helper_skills: usersTable.helper_skills,
  helper_languages: usersTable.helper_languages,
  helper_qualifications: usersTable.helper_qualifications,
  helper_bio: usersTable.helper_bio,
  helper_vehicle: usersTable.helper_vehicle,
  helper_social_links: usersTable.helper_social_links,
  lat: usersTable.lat,
  lng: usersTable.lng,
  heading: usersTable.heading,
  speed: usersTable.speed,
  trust_score: usersTable.trust_score,
  help_count: usersTable.help_count,
  neighborhood: usersTable.neighborhood,
  city: usersTable.city,
  benevolence_wallet: usersTable.benevolence_wallet,
  goodwill_score: usersTable.goodwill_score,
  specialties: usersTable.specialties,
  phone_masked: usersTable.phone_masked,
  quick_replies: usersTable.quick_replies,
  identity_verified: usersTable.identity_verified,
  identity_verification_status: usersTable.identity_verification_status,
  background_check_status: usersTable.background_check_status,
  background_check_completed_at: usersTable.background_check_completed_at,
  stripe_identity_session_id: usersTable.stripe_identity_session_id,
  panic_contacts: usersTable.panic_contacts,
  passive_check_interval_min: usersTable.passive_check_interval_min,
  is_admin: usersTable.is_admin,
  token_version: usersTable.token_version,
  approval_status: usersTable.approval_status,
  approval_reviewed_by: usersTable.approval_reviewed_by,
  approval_reviewed_at: usersTable.approval_reviewed_at,
  account_type: usersTable.account_type,
  organization_name: usersTable.organization_name,
  organization_description: usersTable.organization_description,
  created_at: usersTable.created_at,
  updated_at: usersTable.updated_at,
} as const;
