import { Router, type IRouter } from "express";
import healthRouter from "./health";
import verificationRouter from "./verification";
import usersRouter from "./users";
import requestsRouter from "./requests";
import helpersRouter from "./helpers";
import navigationRouter from "./navigation";
import pushRouter from "./push";
import stripeRouter from "./stripe";
import leaderboardRouter from "./leaderboard";
import gratitudeRouter from "./gratitude";
import reportsRouter from "./reports";
import civicRouter from "./civic";
import adminAnalyticsRouter from "./admin-analytics";
import adminCommunitiesRouter from "./admin-communities";
import communitiesRouter from "./communities";
import crisisRouter from "./crisis";
import recurringRouter from "./recurring";
import communityNeighborhoodsRouter from "./community-neighborhoods";
import regionCrisisResourcesRouter from "./region-crisis-resources";
import niaContextRouter from "./nia-context";
import niaVoiceRouter from "./nia-voice";
import niaProxyRouter from "./nia-proxy";
import poolRouter from "./pool";
import businessesRouter from "./businesses";
import govSponsorsRouter from "./gov-sponsors";
import backgroundChecksRouter from "./background-checks";
import walletRouter from "./wallet";
import googleAuthRouter from "./google-auth";
import checkinRouter from "./checkin";
import disputesRouter from "./disputes";
import impactRouter from "./impact";
import griotRouter from "./griot";
import audioCirclesRouter from "./audio-circles";
import coverageInterestRouter from "./coverage-interest";

const router: IRouter = Router();

router.use(healthRouter);
router.use(verificationRouter);
router.use(usersRouter);
router.use(requestsRouter);
router.use(helpersRouter);
router.use(navigationRouter);
router.use(pushRouter);
router.use(stripeRouter);
router.use(leaderboardRouter);
router.use(gratitudeRouter);
router.use(reportsRouter);
router.use(civicRouter);
router.use(adminAnalyticsRouter);
router.use(adminCommunitiesRouter);
router.use(communitiesRouter);
router.use(crisisRouter);
router.use(recurringRouter);
router.use(communityNeighborhoodsRouter);
router.use(regionCrisisResourcesRouter);
router.use(niaContextRouter);
router.use(niaVoiceRouter);
router.use(niaProxyRouter);
router.use(poolRouter);
router.use(businessesRouter);
router.use(govSponsorsRouter);
router.use(backgroundChecksRouter);
router.use(walletRouter);
router.use(googleAuthRouter);
router.use("/checkin", checkinRouter);
router.use(disputesRouter);
router.use(impactRouter);
router.use(griotRouter);
router.use(audioCirclesRouter);
router.use(coverageInterestRouter);

export default router;
