import { expect, test, type APIRequestContext, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import fs from "node:fs";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

const enabled = process.env.MEDIA_PLATFORM_V21_BROWSER_SMOKE === "1";
const productionGateConfirmed = process.env.CONFIRM_MEDIA_PLATFORM_V21_PRODUCTION_GATE === "1";
const contextKind = process.env.MEDIA_SMOKE_CONTEXT_KIND;
const contextId = Number(process.env.MEDIA_SMOKE_CONTEXT_ID);
const expectedCommit = process.env.EXPECTED_COMMIT?.trim().toLowerCase();
const userState = process.env.USER_A_STATE;
const unauthorizedState = process.env.USER_B_STATE;

const png = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
  "base64",
);

// A fallback fixture is retained for environments without generated bytes;
// the test replaces it with a clean FFmpeg-generated file before upload.
let video = Buffer.from(
  "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAXCbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAAMgAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAq90cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAAMgAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAABAAAAAQAAAAAAAkZlZHQAAAAAGZWxzdAAAAAAAAAAEAAADIAAAEAAABAAAAAAInbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAyAAAACgBVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAAB0m1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAZJzdGJsAAAAvnN0c2QAAAAAAAAAAQAAAK5hdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAABAAEABIAAAASAAAAAAAAAABFUxhdmM2MC4zMS4xMDIgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAANGF2Y0MBZAAK/+EAF2dkAAqs2V7ARAAAAwAEAAADAMg8SJZYAQAGaOvjyyLA/fj4AAAAABBwYXNwAAAAAQAAAAEAAAAUYnRydAAAAAAAAHTgAAB04AAAABhzdHRzAAAAAAAAAAEAAAAFAAACAAAAABRzdHNzAAAAAAAAAAEAAAABAAAAOGN0dHMAAAAAAAAABQAAAAEAAAQAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAAoc3RzYwAAAAAAAAACAAAAAQAAAAMAAAABAAAAAgAAAAIAAAABAAAAKHN0c3oAAAAAAAAAAAAAAAUAAAK8AAAADAAAAAwAAAAMAAAADAAAABhzdGNvAAAAAAAAAAIAAAYHAAAI3wAAAj10cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAACAAAAAAAAAIAAAAAAAAAAAAAAAAEBAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAACAAAAEAAABAAAAAAG1bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAfQAAACABVxAAAAAAALWhkbHIAAAAAAAAAAHNvdW4AAAAAAAAAAAAAAABTb3VuZEhhbmRsZXIAAAABYG1pbmYAAAAQc21oZAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABJHN0YmwAAAB+c3RzZAAAAAAAAAABAAAAbm1wNGEAAAAAAAAAAQAAAAAAAAAAAAEAEAAAAAAfQAAAAAAANmVzZHMAAAAAA4CAgCUAAgAEgICAF0AVAAAAAAC7gAAAAw0FgICABRWIVuUABoCAgAECAAAAFGJ0cnQAAAAAAAC7gAAAAw0AAAAYc3R0cwAAAAAAAAABAAAAAgAABAAAAAAcc3RzYwAAAAAAAAABAAAAAQAAAAEAAAABAAAAHHN0c3oAAAAAAAAAAAAAAAIAAAAVAAAABAAAABhzdGNvAAAAAAAAAAIAAAXyAAAI2wAAABpzZ3BkAQAAAHJvbGwAAAACAAAAAf//AAAAHHNiZ3AAAAAAcm9sbAAAAAEAAAACAAAAAQAAAGJ1ZHRhAAAAWm1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAALWlsc3QAAAAlqXRvbwAAAB1kYXRhAAAAAQAAAABMYXZmNjAuMTYuMTAwAAAACGZyZWUAAAMNbWRhdN4CAExhdmM2MC4zMS4xMDIAAjBADgAAAqAGBf//nNxF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjQgLSBILjI2NC9NUEVHLTQgQVZDIGNvZGVjIC0gQ29weWxlZnQgMjAwMy0yMDI1IC0gaHR0cDovL3d3dy52aWRlb2xhbi5vcmcveDI2NDAuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFseXNlPTB4MzoweDExMyBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MSBxY3FtPTAgZGVhZHpvbWU9MjEsMTEgZmFzdF9za2lwPTEgY2hyb21hX3FwX29mZnNldD0tMiB0aHJlYWRzPTEgbG9vaWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0xIGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBibWZyYW1lcz0zIGJfcHlyYW1pZD0yIGJfYWRhcHQ9MSBiX2JpYXM9MCBkaXJlY3Q9MSB3ZWlnaHQ9MSBvcGVuX2dvcD0wIHdlaWdodHA9MiBrZXlpbnQ9MjUwIGtleWludF9taW49MjUgc2NlbmVjdD00MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTQwIHJjPWNyZiBtYnRyZWU9MSBjcmY9MjMuMCBxY29tcGE9MC42MCBxcG1pbj0wIHFwbWF4PTY5IHFwc3RlcD00IGlwX3JhdGlvPTEuNDAgYXE9MToxLjAwAIAAAAAUZYiEADP//t8y+BTWhQ50QjNkdL8AAAAIQZokbEK//sAAAAAIQZ5CeIX/wYEBGCAHAAAACAGeYXRCv8SAAAAACAGeY2pCv8SB",
  "base64",
);

type MediaAsset = {
  id: number;
  media_type: string;
  status: string;
  media_url: string;
  thumbnail_url: string | null;
  variant_ready?: boolean;
};

const execFileAsync = promisify(execFile);

async function createVideoFixture(): Promise<Buffer> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "niakofa-media-e2e-"));
  const output = path.join(tempDir, "fixture.mp4");
  try {
    await execFileAsync("ffmpeg", [
      "-hide_banner", "-loglevel", "error",
      "-f", "lavfi", "-i", "color=c=blue:s=16x16:d=0.2",
      "-f", "lavfi", "-i", "anullsrc=r=8000:cl=mono",
      "-shortest", "-frames:v", "5",
      "-c:v", "libx264", "-pix_fmt", "yuv420p",
      "-c:a", "aac", "-movflags", "+faststart", "-y", output,
    ], { timeout: 15_000 });
    return await readFile(output);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

function storageStateToken(statePath: string): string {
  const state = JSON.parse(fs.readFileSync(statePath, "utf8")) as {
    origins?: Array<{ localStorage?: Array<{ name: string; value: string }> }>;
  };
  const token = state.origins
    ?.flatMap((origin) => origin.localStorage ?? [])
    .find((entry) => entry.name === "niakofa_token")?.value;
  if (!token) throw new Error(`Authenticated storage state has no Niakofa token: ${statePath}`);
  return token;
}

async function authHeaders(page: Page): Promise<Record<string, string>> {
  const state = await page.context().storageState();
  const token = state.origins
    .flatMap((origin) => origin.localStorage ?? [])
    .find((entry) => entry.name === "niakofa_token")?.value;
  if (!token) throw new Error("Authenticated storage state has no Niakofa token.");
  return { Authorization: `Bearer ${token}` };
}

async function jsonResponse<T>(
  request: APIRequestContext,
  pathname: string,
  headers: Record<string, string>,
): Promise<T> {
  const response = await request.get(pathname, { headers });
  expect(response.ok(), `${pathname} should return a successful response`).toBeTruthy();
  return response.json() as Promise<T>;
}

async function waitForAsset(
  request: APIRequestContext,
  headers: Record<string, string>,
  assetId: number,
  requiredVariant: boolean,
): Promise<MediaAsset> {
  let latest: MediaAsset | undefined;
  await expect.poll(async () => {
    const payload = await jsonResponse<{ assets?: MediaAsset[] }>(
      request,
      `/api/media-assets/shared?contextKind=${encodeURIComponent(String(contextKind))}&contextId=${contextId}`,
      headers,
    );
    latest = payload.assets?.find((asset) => asset.id === assetId);
    if (!latest) return "missing";
    return [
      latest.status,
      latest.thumbnail_url ? "thumbnail" : "no-thumbnail",
      latest.variant_ready ? "variant" : "no-variant",
    ].join(":");
  }, { timeout: 120_000, intervals: [1_000, 2_000, 5_000] }).toBe(
    requiredVariant ? "ready:thumbnail:variant" : "ready:thumbnail:no-variant",
  );
  if (!latest) throw new Error(`Media asset ${assetId} was not returned after processing.`);
  return latest;
}

async function uploadAndComplete(
  request: APIRequestContext,
  headers: Record<string, string>,
  input: {
    body: Buffer;
    mediaType: "photo" | "video";
    mimeType: string;
    originalName: string;
  },
): Promise<number> {
  const init = await request.post("/api/media-assets/uploads", {
    data: {
      contextKind,
      contextId,
      mediaType: input.mediaType,
      mimeType: input.mimeType,
      originalName: input.originalName,
      byteSize: input.body.length,
    },
    headers,
  });
  expect(init.status()).toBe(201);
  const initialized = await init.json() as {
    media_asset_id: number;
    upload: { url: string; headers: Record<string, string> };
    complete_url: string;
  };

  const uploadUrl = new URL(
    initialized.upload.url,
    process.env.PLAYWRIGHT_BASE_URL ?? "http://127.0.0.1:5000",
  );
  const upload = await request.put(uploadUrl.toString(), {
    data: input.body,
    headers: initialized.upload.headers,
  });
  expect(upload.status(), `${input.mediaType} object upload should succeed`).toBeLessThan(300);

  const complete = await request.post(initialized.complete_url, { headers });
  expect(complete.status(), `${input.mediaType} upload should queue processing`).toBe(202);
  return initialized.media_asset_id;
}

test.describe("authenticated universal media smoke", () => {
  test.use({ storageState: userState });

  test.skip(
    !enabled ||
      !productionGateConfirmed ||
      !userState ||
      !contextKind ||
      !Number.isSafeInteger(contextId) ||
      contextId < 1,
    "Requires MEDIA_PLATFORM_V21_BROWSER_SMOKE=1, CONFIRM_MEDIA_PLATFORM_V21_PRODUCTION_GATE=1, USER_A_STATE, MEDIA_SMOKE_CONTEXT_KIND, and MEDIA_SMOKE_CONTEXT_ID.",
  );

  test.beforeAll(async ({ request }) => {
    const health = await request.get("/api/healthz");
    expect(health.ok()).toBeTruthy();
    const healthBody = await health.json() as {
      storage_readiness?: { media_platform_flag?: boolean; cloud_configured?: boolean; credentials_present?: boolean };
    };
    expect(healthBody.storage_readiness?.cloud_configured).toBe(true);
    expect(healthBody.storage_readiness?.credentials_present).toBe(true);
    expect(healthBody.storage_readiness?.media_platform_flag).toBe(true);

    const readiness = await request.get("/api/readiness");
    expect(readiness.ok()).toBeTruthy();
    expect((await readiness.json()).ready).toBe(true);

    if (expectedCommit) {
      const version = await request.get("/api/version");
      expect(version.ok()).toBeTruthy();
      const deployedCommit = String((await version.json()).commit ?? "").toLowerCase();
      expect(
        deployedCommit.startsWith(expectedCommit) || expectedCommit.startsWith(deployedCommit),
        `deployed commit ${deployedCommit} should match EXPECTED_COMMIT ${expectedCommit}`,
      ).toBe(true);
    }
  });

  test("uploads, finalizes, processes, persists variants, and retrieves photo/video media", async ({ page, request }) => {
    const headers = await authHeaders(page);
    video = await createVideoFixture();
    const photoId = await uploadAndComplete(request, headers, {
      body: png,
      mediaType: "photo",
      mimeType: "image/png",
      originalName: "production-media-smoke.png",
    });
    const photo = await waitForAsset(request, headers, photoId, false);
    expect(photo.status).toBe("ready");
    expect(photo.thumbnail_url).toBe(`/api/media-assets/${photoId}/thumbnail`);

    const photoPlayback = await request.get(photo.media_url, { headers });
    expect(photoPlayback.status()).toBe(200);
    expect(photoPlayback.headers()["content-type"]).toContain("image/png");
    const thumbnail = await request.get(photo.thumbnail_url, { headers });
    expect(thumbnail.status()).toBe(200);
    expect(thumbnail.headers()["content-type"]).toContain("image/jpeg");

    const videoId = await uploadAndComplete(request, headers, {
      body: video,
      mediaType: "video",
      mimeType: "video/mp4",
      originalName: "production-media-smoke.mp4",
    });
    const videoAsset = await waitForAsset(request, headers, videoId, true);
    expect(videoAsset.status).toBe("ready");
    expect(videoAsset.variant_ready).toBe(true);

    const videoPlayback = await request.get(videoAsset.media_url, { headers });
    expect(videoPlayback.status()).toBe(200);
    expect(videoPlayback.headers()["content-type"]).toContain("video/mp4");

    if (unauthorizedState) {
      const unauthorizedHeaders = { Authorization: `Bearer ${storageStateToken(unauthorizedState)}` };
      for (const assetId of [photoId, videoId]) {
        const response = await request.get(`/api/media-assets/${assetId}`, { headers: unauthorizedHeaders });
        expect(response.status(), `USER_B_STATE must not retrieve asset ${assetId}`).toBe(404);
      }
    }
  });
});
