import { expect, test, type APIRequestContext, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import fs from "node:fs";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

const enabled = process.env.MEDIA_PLATFORM_V21_BROWSER_SMOKE === "1";
const productionGateConfirmed = process.env.CONFIRM_MEDIA_PLATFORM_V21_PRODUCTION_GATE === "1";
const retainTestMediaRequested = process.env.MEDIA_CERT_RETAIN_TEST_MEDIA === "1";
const retainProductionMedia =
  retainTestMediaRequested &&
  process.env.CONFIRM_RETAIN_PRODUCTION_MEDIA === "1";
const contextKind = process.env.MEDIA_SMOKE_CONTEXT_KIND;
const contextId = Number(process.env.MEDIA_SMOKE_CONTEXT_ID);
const expectedCommit = process.env.EXPECTED_COMMIT?.trim().toLowerCase();
const userState = process.env.USER_A_STATE;
const unauthorizedState = process.env.USER_B_STATE;

const png = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
  "base64",
);

// A fallback fixture is retained for environments without generated bytes;
// the test replaces it with a clean FFmpeg-generated file before upload.
let video: Buffer = Buffer.from(
  "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAXCbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAAMgAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAq90cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAAMgAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAABAAAAAQAAAAAAAkZlZHQAAAAAGZWxzdAAAAAAAAAAEAAADIAAAEAAABAAAAAAInbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAyAAAACgBVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAAB0m1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAZJzdGJsAAAAvnN0c2QAAAAAAAAAAQAAAK5hdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAABAAEABIAAAASAAAAAAAAAABFUxhdmM2MC4zMS4xMDIgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAANGF2Y0MBZAAK/+EAF2dkAAqs2V7ARAAAAwAEAAADAMg8SJZYAQAGaOvjyyLA/fj4AAAAABBwYXNwAAAAAQAAAAEAAAAUYnRydAAAAAAAAHTgAAB04AAAABhzdHRzAAAAAAAAAAEAAAAFAAACAAAAABRzdHNzAAAAAAAAAAEAAAABAAAAOGN0dHMAAAAAAAAABQAAAAEAAAQAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAAoc3RzYwAAAAAAAAACAAAAAQAAAAMAAAABAAAAAgAAAAIAAAABAAAAKHN0c3oAAAAAAAAAAAAAAAUAAAK8AAAADAAAAAwAAAAMAAAADAAAABhzdGNvAAAAAAAAAAIAAAYHAAAI3wAAAj10cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAACAAAAAAAAAIAAAAAAAAAAAAAAAAEBAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAACAAAAEAAABAAAAAAG1bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAfQAAACABVxAAAAAAALWhkbHIAAAAAAAAAAHNvdW4AAAAAAAAAAAAAAABTb3VuZEhhbmRsZXIAAAABYG1pbmYAAAAQc21oZAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABJHN0YmwAAAB+c3RzZAAAAAAAAAABAAAAbm1wNGEAAAAAAAAAAQAAAAAAAAAAAAEAEAAAAAAfQAAAAAAANmVzZHMAAAAAA4CAgCUAAgAEgICAF0AVAAAAAAC7gAAAAw0FgICABRWIVuUABoCAgAECAAAAFGJ0cnQAAAAAAAC7gAAAAw0AAAAYc3R0cwAAAAAAAAABAAAAAgAABAAAAAAcc3RzYwAAAAAAAAABAAAAAQAAAAEAAAABAAAAHHN0c3oAAAAAAAAAAAAAAAIAAAAVAAAABAAAABhzdGNvAAAAAAAAAAIAAAXyAAAI2wAAABpzZ3BkAQAAAHJvbGwAAAACAAAAAf//AAAAHHNiZ3AAAAAAcm9sbAAAAAEAAAACAAAAAQAAAGJ1ZHRhAAAAWm1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAALWlsc3QAAAAlqXRvbwAAAB1kYXRhAAAAAQAAAABMYXZmNjAuMTYuMTAwAAAACGZyZWUAAAMNbWRhdN4CAExhdmM2MC4zMS4xMDIAAjBADgAAAqAGBf//nNxF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjQgLSBILjI2NC9NUEVHLTQgQVZDIGNvZGVjIC0gQ29weWxlZnQgMjAwMy0yMDI1IC0gaHR0cDovL3d3dy52aWRlb2xhbi5vcmcveDI2NDAuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFseXNlPTB4MzoweDExMyBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MSBxY3FtPTAgZGVhZHpvbWU9MjEsMTEgZmFzdF9za2lwPTEgY2hyb21hX3FwX29mZnNldD0tMiB0aHJlYWRzPTEgbG9vaWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0xIGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBibWZyYW1lcz0zIGJfcHlyYW1pZD0yIGJfYWRhcHQ9MSBiX2JpYXM9MCBkaXJlY3Q9MSB3ZWlnaHQ9MSBvcGVuX2dvcD0wIHdlaWdodHA9MiBrZXlpbnQ9MjUwIGtleWludF9taW49MjUgc2NlbmVjdD00MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTQwIHJjPWNyZiBtYnRyZWU9MSBjcmY9MjMuMCBxY29tcGE9MC42MCBxcG1pbj0wIHFwbWF4PTY5IHFwc3RlcD00IGlwX3JhdGlvPTEuNDAgYXE9MToxLjAwAIAAAAAUZYiEADP//t8y+BTWhQ50QjNkdL8AAAAIQZokbEK//sAAAAAIQZ5CeIX/wYEBGCAHAAAACAGeYXRCv8SAAAAACAGeY2pCv8SB",
  "base64",
);

type MediaAsset = {
  id: number;
  media_type: string;
  status: string;
  media_url: string;
  thumbnail_url: string | null;
  variant_ready?: boolean;
};

const execFileAsync = promisify(execFile);

async function createVideoFixture(): Promise<Buffer> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "niakofa-media-e2e-"));
  const output = path.join(tempDir, "fixture.mp4");
  try {
    await execFileAsync("ffmpeg", [
      "-hide_banner", "-loglevel", "error",
      "-f", "lavfi", "-i", "color=c=blue:s=16x16:d=0.2",
      "-f", "lavfi", "-i", "anullsrc=r=8000:cl=mono",
      "-shortest", "-frames:v", "5",
      "-c:v", "libx264", "-pix_fmt", "yuv420p",
      "-c:a", "aac", "-movflags", "+faststart", "-y", output,
    ], { timeout: 15_000 });
    return await readFile(output);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

function storageStateToken(statePath: string): string {
  const state = JSON.parse(fs.readFileSync(statePath, "utf8")) as {
    origins?: Array<{ localStorage?: Array<{ name: string; value: string }> }>;
  };
  const token = state.origins
    ?.flatMap((origin) => origin.localStorage ?? [])
    .find((entry) => entry.name === "niakofa_token")?.value;
  if (!token) throw new Error(`Authenticated storage state has no Niakofa token: ${statePath}`);
  return token;
}

async function authHeaders(page: Page): Promise<Record<string, string>> {
  const state = await page.context().storageState();
  const token = state.origins
    .flatMap((origin) => origin.localStorage ?? [])
    .find((entry) => entry.name === "niakofa_token")?.value;
  if (!token) throw new Error("Authenticated storage state has no Niakofa token.");
  return { Authorization: `Bearer ${token}` };
}

async function jsonResponse<T>(
  request: APIRequestContext,
  pathname: string,
  headers: Record<string, string>,
): Promise<T> {
  const response = await request.get(pathname, { headers });
  expect(response.ok(), `${pathname} should return a successful response`).toBeTruthy();
  return response.json() as Promise<T>;
}

async function waitForAsset(
  request: APIRequestContext,
  headers: Record<string, string>,
  assetId: number,
  requiredVariant: boolean,
): Promise<MediaAsset> {
  let latest: MediaAsset | undefined;
  await expect.poll(async () => {
    const payload = await jsonResponse<{ assets?: MediaAsset[] }>(
      request,
      `/api/media-assets/shared?contextKind=${encodeURIComponent(String(contextKind))}&contextId=${contextId}`,
      headers,
    );
    latest = payload.assets?.find((asset) => asset.id === assetId);
    if (!latest) return "missing";
    return [
      latest.status,
      latest.thumbnail_url ? "thumbnail" : "no-thumbnail",
      latest.variant_ready ? "variant" : "no-variant",
    ].join(":");
  }, { timeout: 120_000, intervals: [1_000, 2_000, 5_000] }).toBe(
    requiredVariant ? "ready:thumbnail:variant" : "ready:thumbnail:no-variant",
  );
  if (!latest) throw new Error(`Media asset ${assetId} was not returned after processing.`);
  return latest;
}

async function uploadAndComplete(
  request: APIRequestContext,
  headers: Record<string, string>,
  input: {
    body: Buffer;
    mediaType: "photo" | "video";
    mimeType: string;
    originalName: string;
    onCreated?: (mediaAssetId: number) => void;
  },
): Promise<number> {
  const init = await request.post("/api/media-assets/uploads", {
    data: {
      contextKind,
      contextId,
      mediaType: input.mediaType,
      mimeType: input.mimeType,
      originalName: input.originalName,
      byteSize: input.body.length,
    },
    headers,
  });
  expect(init.status()).toBe(201);
  const initialized = await init.json() as {
    media_asset_id: number;
    upload: { url: string; headers: Record<string, string> };
    complete_url: string;
  };
  input.onCreated?.(initialized.media_asset_id);

  const baseUrl = process.env.PLAYWRIGHT_BASE_URL ?? "http://127.0.0.1:5000";
  const uploadUrl = new URL(initialized.upload.url, baseUrl);
  const upload = await request.put(uploadUrl.toString(), {
    data: input.body,
    headers: {
      ...initialized.upload.headers,
      ...(uploadUrl.origin === new URL(baseUrl).origin ? headers : {}),
    },
  });
  expect(upload.status(), `${input.mediaType} object upload should succeed (asset ${initialized.media_asset_id})`).toBeLessThan(300);

  const complete = await request.post(initialized.complete_url, { headers });
  expect(complete.status(), `${input.mediaType} upload should queue processing`).toBe(202);
  return initialized.media_asset_id;
}

test.describe("authenticated universal media smoke", () => {
  test.use({ storageState: userState });

  test.skip(
    !enabled ||
      !productionGateConfirmed ||
      !userState ||
      !unauthorizedState ||
      !/^[0-9a-f]{40}$/.test(expectedCommit ?? "") ||
      !contextKind ||
      !Number.isSafeInteger(contextId) ||
      contextId < 1,
    "Requires activated media, both approved account states, a full expected commit, and an approved context.",
  );

  test.beforeAll(async ({ request }) => {
    const health = await request.get("/api/healthz");
    expect(health.ok()).toBeTruthy();
    const healthBody = await health.json() as {
      storage_readiness?: { media_platform_flag?: boolean; cloud_configured?: boolean; credentials_present?: boolean };
    };
    expect(healthBody.storage_readiness?.cloud_configured).toBe(true);
    expect(healthBody.storage_readiness?.credentials_present).toBe(true);
    expect(healthBody.storage_readiness?.media_platform_flag).toBe(true);

    const readiness = await request.get("/api/readiness");
    expect(readiness.ok()).toBeTruthy();
    expect((await readiness.json()).ready).toBe(true);

    const version = await request.get("/api/version");
    expect(version.ok()).toBeTruthy();
    const deployedCommit = String((await version.json()).commit ?? "").toLowerCase();
    expect(deployedCommit, "The deployed commit must exactly match the intended release.").toBe(expectedCommit);
  });

  test("uploads, finalizes, processes, persists variants, and retrieves photo/video media", async ({ page, request }) => {
    test.setTimeout(180_000);
    test.skip(
      retainTestMediaRequested,
      "This universal smoke includes a deletion fixture and cannot run in retained-media mode.",
    );
    const headers = await authHeaders(page);
    video = await createVideoFixture();
    const photoId = await uploadAndComplete(request, headers, {
      body: png,
      mediaType: "photo",
      mimeType: "image/png",
      originalName: "production-media-smoke.png",
    });
    const photo = await waitForAsset(request, headers, photoId, false);
    expect(photo.status).toBe("ready");
    expect(photo.thumbnail_url).toBe(`/api/media-assets/${photoId}/thumbnail`);

    const photoPlayback = await request.get(photo.media_url, { headers });
    expect(photoPlayback.status()).toBe(200);
    expect(photoPlayback.headers()["content-type"]).toContain("image/png");
    const thumbnail = await request.get(photo.thumbnail_url, { headers });
    expect(thumbnail.status()).toBe(200);
    expect(thumbnail.headers()["content-type"]).toContain("image/jpeg");

    const videoId = await uploadAndComplete(request, headers, {
      body: video,
      mediaType: "video",
      mimeType: "video/mp4",
      originalName: "production-media-smoke.mp4",
    });
    const videoAsset = await waitForAsset(request, headers, videoId, true);
    expect(videoAsset.status).toBe("ready");
    expect(videoAsset.variant_ready).toBe(true);

    const videoPlayback = await request.get(videoAsset.media_url, { headers });
    expect(videoPlayback.status()).toBe(200);
    expect(videoPlayback.headers()["content-type"]).toContain("video/mp4");

    const unauthorizedHeaders = { Authorization: `Bearer ${storageStateToken(unauthorizedState!)}` };
    if (!photo.thumbnail_url) throw new Error("The photo thumbnail is missing.");
    for (const url of [photo.media_url, photo.thumbnail_url, videoAsset.media_url]) {
      const response = await request.get(url, { headers: unauthorizedHeaders });
      expect(response.status(), `USER_B_STATE must not retrieve ${url}`).toBe(404);
    }

    // Use a separate disposable photo to exercise user-facing deletion while
    // leaving the two retained playback fixtures available for review.
    const deletionId = await uploadAndComplete(request, headers, {
      body: png,
      mediaType: "photo",
      mimeType: "image/png",
      originalName: "production-media-delete-smoke.png",
    });
    const deletionAsset = await waitForAsset(request, headers, deletionId, false);
    const deletion = await request.delete(`/api/media-assets/${deletionId}`, { headers });
    expect(deletion.status(), "the owner should be able to delete the disposable media asset").toBe(204);
    const deletedOriginal = await request.get(deletionAsset.media_url, { headers });
    expect(deletedOriginal.status(), "deleted original media must not be playable").toBe(404);
    if (!deletionAsset.thumbnail_url) throw new Error("The deletion fixture has no thumbnail.");
    const deletedThumbnail = await request.get(deletionAsset.thumbnail_url, { headers });
    expect(deletedThumbnail.status(), "deleted thumbnails must not be playable").toBe(404);
    const remaining = await jsonResponse<{ assets?: MediaAsset[] }>(
      request,
      `/api/media-assets/shared?contextKind=${encodeURIComponent(String(contextKind))}&contextId=${contextId}`,
      headers,
    );
    expect(remaining.assets?.some((asset) => asset.id === deletionId)).toBe(false);
    process.stdout.write(`MEDIA_CERT_RETAINED_ASSETS photo=${photoId} video=${videoId} deleted=${deletionId}\n`);
  });

  test("photo-only diagnostic uploads and verifies exactly one photo", async ({ page, request }) => {
    test.setTimeout(180_000);
    test.skip(
      process.env.MEDIA_CERT_PHOTO_ONLY_SMOKE !== "1",
      "Requires the explicit photo-only production diagnostic gate.",
    );
    expect(
      !retainTestMediaRequested || retainProductionMedia,
      "Retaining production test media requires explicit operator confirmation.",
    ).toBeTruthy();
    expect(contextKind, "The photo-only diagnostic must use an approved Hub context.").toBe("hub");
    const headers = await authHeaders(page);
    const otherHeaders = { Authorization: `Bearer ${storageStateToken(unauthorizedState!)}` };
    const sharedPath =
      `/api/media-assets/shared?contextKind=${encodeURIComponent(String(contextKind))}&contextId=${contextId}`;
    const ownerBefore = await jsonResponse<{ assets?: MediaAsset[] }>(request, sharedPath, headers);
    expect(ownerBefore.assets ?? [], "the approved test Hub must be empty before upload").toHaveLength(0);
    const otherBefore = await request.get(sharedPath, { headers: otherHeaders });
    expect(otherBefore.status(), "the other approved account must remain outside the test Hub").toBe(404);

    let photoId: number | undefined;
    let testFailed = false;
    try {
      photoId = await uploadAndComplete(request, headers, {
        body: png,
        mediaType: "photo",
        mimeType: "image/png",
        originalName: "production-photo-diagnostic.png",
        onCreated: (createdId) => { photoId = createdId; },
      });
      process.stdout.write(`MEDIA_CERT_PHOTO_ONLY_CREATED asset=${photoId}\n`);
      const photo = await waitForAsset(request, headers, photoId, false);
      expect(photo.status).toBe("ready");
      expect(photo.thumbnail_url).toBe(`/api/media-assets/${photoId}/thumbnail`);

      const original = await request.get(photo.media_url, { headers });
      expect(original.status()).toBe(200);
      expect(original.headers()["content-type"]).toContain("image/png");
      const thumbnail = await request.get(photo.thumbnail_url!, { headers });
      expect(thumbnail.status()).toBe(200);
      expect(thumbnail.headers()["content-type"]).toContain("image/jpeg");

      const otherAfter = await request.get(sharedPath, { headers: otherHeaders });
      expect(otherAfter.status(), "the other approved account must not see the uploaded photo").toBe(404);
      const otherOriginal = await request.get(photo.media_url, { headers: otherHeaders });
      expect(otherOriginal.status(), "the other approved account must not retrieve the uploaded photo").toBe(404);
      const otherThumbnail = await request.get(photo.thumbnail_url!, { headers: otherHeaders });
      expect(otherThumbnail.status(), "the other approved account must not retrieve the thumbnail").toBe(404);
      process.stdout.write(`MEDIA_CERT_PHOTO_ONLY_PROCESSED asset=${photoId}\n`);
    } catch (error) {
      testFailed = true;
      throw error;
    } finally {
      if (photoId !== undefined) {
        try {
          if (retainProductionMedia) {
            const ownerAfter = await jsonResponse<{ assets?: MediaAsset[] }>(request, sharedPath, headers);
            if (!ownerAfter.assets?.some((asset) => asset.id === photoId)) {
              throw new Error("The retained photo is missing from the approved test Hub.");
            }
            const otherAfter = await request.get(sharedPath, { headers: otherHeaders });
            if (otherAfter.status() !== 404) {
              throw new Error("The other approved account gained access to the test Hub.");
            }
            process.stdout.write(`MEDIA_CERT_PHOTO_ONLY_RETAINED asset=${photoId} hub=${contextId}\n`);
          } else {
            const deletion = await request.delete(`/api/media-assets/${photoId}`, { headers });
            if (deletion.status() !== 204) {
              throw new Error(`Photo diagnostic cleanup returned HTTP ${deletion.status()}.`);
            }
            const ownerAfter = await jsonResponse<{ assets?: MediaAsset[] }>(request, sharedPath, headers);
            if (ownerAfter.assets?.some((asset) => asset.id === photoId)) {
              throw new Error("Photo diagnostic asset remained in the approved test Hub after deletion.");
            }
            const otherCleanupCheck = await request.get(sharedPath, { headers: otherHeaders });
            if (otherCleanupCheck.status() !== 404) {
              throw new Error("The other approved account gained access to the test Hub.");
            }
            process.stdout.write(`MEDIA_CERT_PHOTO_ONLY_CLEANED asset=${photoId}\n`);
          }
        } catch {
          const outcome = retainProductionMedia ? "RETAIN_VERIFY_FAILED" : "CLEANUP_FAILED";
          process.stderr.write(`MEDIA_CERT_PHOTO_ONLY_${outcome} asset=${photoId}\n`);
          if (!testFailed) {
            const message = retainProductionMedia
              ? "Photo-only production diagnostic could not verify the retained asset."
              : "Photo-only production diagnostic could not verify asset cleanup.";
            throw new Error(message);
          }
        }
      }
    }
  });
});
