// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/niakofa-moments/Current.tsx": () => import("../components/mockups/niakofa-moments/Current.tsx"),
  "./components/mockups/niakofa-moments/VerticalFeed.tsx": () => import("../components/mockups/niakofa-moments/VerticalFeed.tsx"),
  "./components/mockups/spark-studio/Current.tsx": () => import("../components/mockups/spark-studio/Current.tsx"),
  "./components/mockups/spark-studio/SparkStudioDirection.tsx": () => import("../components/mockups/spark-studio/SparkStudioDirection.tsx"),
  "./components/mockups/spark-composer-current/CurrentAppSource.tsx": () => import("../components/mockups/spark-composer-current/CurrentAppSource.tsx")
};
