-- 0071_fix_duplicate_cascade_constraints.sql
--
-- CRITICAL follow-up to 0068/0069. Those migrations intended to fix
-- content-vs-ownership cascade-delete bugs (griot_stories.author_id,
-- civic_needs.posted_by_user_id, audio_circle_sessions.host_id,
-- diaspora_hub_pledges.pledged_by) by dropping the old CASCADE constraint
-- and re-adding it as SET NULL.
--
-- Verified against pg_constraint: each of those tables actually had TWO
-- foreign key constraints on the same column (one hand-written, one
-- auto-generated by an earlier `drizzle-kit push`, under two different
-- constraint names). The 0068/0069 migrations only knew about — and only
-- dropped — one of the two names. The second, differently-named CASCADE
-- constraint was never touched and stayed live.
--
-- Empirically verified (see accompanying investigation) that when a column
-- has both a CASCADE and a SET NULL foreign key constraint pointing at the
-- same table, CASCADE wins — the child row is deleted, not nulled. That
-- means all four "fixed" tables were STILL silently destroying real content
-- (stories, civic needs, session recordings, pledge financial records) on
-- account deletion, exactly as before 0068/0069, despite those migrations'
-- intent and commit messages.
--
-- This migration finds and drops every remaining CASCADE-delete duplicate
-- on these columns, leaving only the correct SET NULL constraint.
--
-- Also fixes wallet_cashouts.user_id, a real payout-ledger record that was
-- never audited before: it only ever had a single CASCADE constraint (no
-- app-level delete guard either), so a user with cashout history could
-- still have that financial record destroyed on account deletion. Switched
-- to SET NULL + will be backed by an app-level blocking check, matching the
-- diaspora_hub_pledges pattern.

DO $$
DECLARE
  rec RECORD;
BEGIN
  -- Drop ANY foreign-key constraint on these (table, column) pairs whose
  -- delete action is CASCADE ('c'), keeping the SET NULL ones intact.
  FOR rec IN
    SELECT conrelid::regclass::text AS tbl, conname
    FROM pg_constraint c
    JOIN LATERAL (
      SELECT a.attname
      FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
      JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
    ) cols ON true
    WHERE c.contype = 'f'
      AND c.confdeltype = 'c'
      AND (
        (c.conrelid = 'griot_stories'::regclass AND cols.attname = 'author_id') OR
        (c.conrelid = 'civic_needs'::regclass AND cols.attname = 'posted_by_user_id') OR
        (c.conrelid = 'audio_circle_sessions'::regclass AND cols.attname = 'host_id') OR
        (c.conrelid = 'diaspora_hub_pledges'::regclass AND cols.attname = 'pledged_by')
      )
  LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', rec.tbl, rec.conname);
    RAISE NOTICE 'Dropped stray CASCADE constraint % on %', rec.conname, rec.tbl;
  END LOOP;
END $$;

DO $$
BEGIN
  ALTER TABLE wallet_cashouts ALTER COLUMN user_id DROP NOT NULL;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'wallet_cashouts_user_id_fk') THEN
    ALTER TABLE wallet_cashouts DROP CONSTRAINT wallet_cashouts_user_id_fk;
  END IF;
  ALTER TABLE wallet_cashouts
    ADD CONSTRAINT wallet_cashouts_user_id_fk
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
  RAISE NOTICE 'wallet_cashouts.user_id: CASCADE -> SET NULL';
END $$;
