export const UNIFIED_EVENT_TYPES=["message.created","message.updated","message.read","message.deleted","conversation.created","conversation.updated","conversation.read","typing.started","typing.stopped","presence.changed","request.created","request.updated","request.status_changed","hub.created","hub.updated","hub.membership_changed","story.created","story.reaction","story.reply","story.shared","call.invited","call.accepted","call.rejected","call.ended","nia.message","nia.typing","nia.status"] as const;
export type UnifiedEventType=typeof UNIFIED_EVENT_TYPES[number];
export type UnifiedRealtimeEvent={event_id:string;event_type:UnifiedEventType;occurred_at:string;actor_id:number|null;conversation_id:number|null;conversation_kind:string|null;entity_id:string|null;payload:Record<string,unknown>;};
const legacyMap:Record<string,UnifiedEventType|null>={direct_message:"message.created",chat_message:"message.created",hub_message:"message.created",message_read:"message.read",typing:"typing.started",presence_update:"presence.changed",request_updated:"request.updated",REQUEST_CREATED:"request.created",REQUEST_ACCEPTED:"request.status_changed",REQUEST_CANCELLED:"request.status_changed",community_story_created:"story.created",community_story_reaction:"story.reaction",community_story_viewed:"story.created",direct_call_invite:"call.invited",direct_call_accept:"call.accepted",direct_call_end:"call.ended",nia_typing:"nia.typing",nia_status:"nia.status"};
export function normalizeRealtimeEvent(event:{type:string;payload?:unknown;event_id?:string;occurred_at?:string}):UnifiedRealtimeEvent|null{
 const source=event.type==="unified_event"?event.payload as Partial<UnifiedRealtimeEvent>|undefined:null; const eventType=(source?.event_type??legacyMap[event.type])??null; if(!eventType)return null;
 const payload=(source?.payload??event.payload??{}) as Record<string,unknown>; const num=(v:unknown)=>typeof v==="number"&&Number.isInteger(v)?v:null;
 const conversationId=num(source?.conversation_id)??num(payload.conversation_id)??num(payload.request_id)??num(payload.hub_id)??null; const actorId=num(source?.actor_id)??num(payload.sender_id)??num(payload.user_id)??null;
 return {event_id:source?.event_id??event.event_id??`${event.type}:${JSON.stringify(payload)}`,event_type:eventType,occurred_at:source?.occurred_at??event.occurred_at??new Date().toISOString(),actor_id:actorId,conversation_id:conversationId,conversation_kind:source?.conversation_kind??(event.type==="hub_message"?"hub":event.type==="chat_message"?"request":event.type==="direct_message"||event.type==="message_read"?"direct":null),entity_id:source?.entity_id??(payload.id!=null?String(payload.id):null),payload};
}
export type DurableRealtimeState={cursor:string|null;seen:string[]};
const STORAGE_KEY="niakofa:realtime-cursor:v1"; const SEEN_LIMIT=1000;
export function loadDurableRealtimeState(storage:Storage=localStorage):DurableRealtimeState{try{const raw=storage.getItem(STORAGE_KEY);if(!raw)return{cursor:null,seen:[]};const p=JSON.parse(raw) as Partial<DurableRealtimeState>;return{cursor:typeof p.cursor==="string"?p.cursor:null,seen:Array.isArray(p.seen)?p.seen.filter((v):v is string=>typeof v==="string").slice(-SEEN_LIMIT):[]};}catch{return{cursor:null,seen:[]};}}
export function rememberDurableEvent(state:DurableRealtimeState,eventId:string,storage:Storage=localStorage):DurableRealtimeState{if(state.seen.includes(eventId))return state;const next={cursor:eventId,seen:[...state.seen,eventId].slice(-SEEN_LIMIT)};try{storage.setItem(STORAGE_KEY,JSON.stringify(next));}catch{}return next;}